# Generated by Django 4.1.5 on 2023-01-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_amenities_room_name_alter_amenity_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(),
        ),
    ]
