# Generated by Django 4.1.5 on 2023-01-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_alter_room_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
    ]
